apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: bulkprocessor
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: bulkprocessor-iap
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bulkprocessor-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: bulkprocessor
    ingress.gcp.kubernetes.io/pre-shared-cert: bulkprocessor
spec:
  backend:
    serviceName: bulkprocessor
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bulkprocessor
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"bulkprocessor"}}'
  labels:
    app: bulkprocessor
    env: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: bulkprocessor
    env: dev
